<?php

use Drupal\Core\Database\Database;

function test_one_schema() {
    $schema['test_one_user_stats'] = [
        'fields' => [
            'id' => [
                'type' => 'serial',
                'not null' => TRUE,
            ],
            'type' => [
                'type' => 'varchar',
                'length' => 50,
                'not null' => TRUE,
            ],
            'timestamp' => [
                'type' => 'int',
                'not null' => TRUE,
            ],
            'uid' => [
                'type' => 'int',
                'not null' => TRUE,
            ],
        ],
        'primary key' => ['id'],
    ];
    $schema['test_one_contact'] = [
        'fields' => [
            'id' => [
                'type' => 'serial',
                'not null' => TRUE
            ],
            'mail' => [
                'type' => 'varchar',
                'length' => 50,
                'not null' => TRUE
            ],
            'lastname' => [
                'type' => 'varchar',
                'length' => 50,
                'not null' => TRUE
            ],
            'firstname' => [
                'type' => 'varchar',
                'length' => 50,
                'not null' => TRUE
            ],
            'content' => [
                'type' => 'varchar',
                'length' => 250,
                'not null' => TRUE
            ],
        ],
        'primary key' => ['id'],
    ];
    return $schema;
}

/**
 * @param null $sandbox
 * @return \Drupal\Core\StringTranslation\TranslatableMarkup
 */
function test_one_update_9001(&$sandbox = null)
{
    $schema = Database::getConnection()->schema();

    $spec = [
        'fields' => [
            'id' => [
                'type' => 'serial',
                'not null' => TRUE
            ],
            'mail' => [
                'type' => 'varchar',
                'length' => 50,
                'not null' => TRUE
            ],
            'lastname' => [
                'type' => 'varchar',
                'length' => 50,
                'not null' => TRUE
            ],
            'firstname' => [
                'type' => 'varchar',
                'length' => 50,
                'not null' => TRUE
            ],
            'content' => [
                'type' => 'varchar',
                'length' => 250,
                'not null' => TRUE
            ],
        ],
        'primary key' => ['id'],
    ];

    $schema->createTable('test_one_contact', $spec);
}
